### ISSUE TITLE
add Jason to the nectar project

### ISSUE THREAD

**Issue by DanielBaird** [jcu-eresearch/uniprep#4]

**Comment by DanielBaird** [comment]
@davidjb I think you might be the admin for this nectar project

**Comment by davidjb** [comment]
I did this back when the project started; if he's not got access (or needs a resend of the invite if that's how it works etc) or needs a specific email assigned that's not the CQU one, let me know.

**Comment by DanielBaird** [comment]
I believe it's his j.bell @ cqu account, I've emailed to say he might already have it. If I close this abruptly, it's coz Jason got his access :)

**Comment by jasonbell13** [comment]
Yep – I already have it ☺

**Comment by DanielBaird** [comment]
closing.. (this comment used to have different content, coz I didn't realise the email I was acting on was a "issue comment" email from github.. justification for closing is immediately above)
